# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create!(username: "Alexey_Stakhanov", password: "TonsOfCoal1906" )
User.create!(username: "Alexey_Stakhanov", password: "Guest123" )
User.create!(username: "Ivan_Kozhedub", password: "Guest123" )
User.create!(username: "Yuri_Gagarin", password: "Guest123" )
User.create!(username: "Valentina_Tereshkova", password: "Guest123" )
User.create!(username: "Ivan_Panfilov", password: "Guest123" )
User.create!(username: "Dmitry_Lavrinenko", password: "Guest123" )
User.create!(username: "Vasily_Zaytsev", password: "Guest123" )
User.create!(username: "Lyudmila_Pavlichenko", password: "Guest123" )
User.create!(username: "Mariya_Oktyabrskaya", password: "Guest123" )
User.create!(username: "Georgy_Zhukov", password: "Guest123" )
User.create!(username: "Konstantin_Rokossovsky", password: "Guest123" )
User.create!(username: "Ivan_Konev", password: "Guest123" )
User.create!(username: "Aleksandr_Vasilevsky", password: "Guest123" )
User.create!(username: "Markian_Popov", password: "Guest123" )
User.create!(username: "Kliment_Voroshilov", password: "Guest123" )
User.create!(username: "Ivan_Fedyuninsky", password: "Guest123" )
User.create!(username: "Mikhail_Khozin", password: "Guest123" )
User.create!(username: "Leonid_Govorov", password: "Guest123" )
User.create!(username: "Nikolay_Voronov", password: "Guest123" )
User.create!(username: "Andrey_Yeryomenko", password: "Guest123" )
User.create!(username: "Vasily_Chuikov", password: "Guest123" )
User.create!(username: "Ivan_Petrov", password: "Guest123" )
User.create!(username: "Filipp_Oktyabrskiy", password: "Guest123" )
User.create!(username: "Gordey_Levchenko", password: "Guest123" )
User.create!(username: "Aleksandr_Marinesko", password: "Guest123" )
User.create!(username: "Alexander_Matrosov", password: "Guest123" )
User.create!(username: "Richard_Sorge", password: "Guest123" )
User.create!(username: "Nikolai_Kuznetsov", password: "Guest123" )
User.create!(username: "Zhambyl_Tulaev", password: "Guest123" )
User.create!(username: "Anna_Yegorova", password: "Guest123" )
User.create!(username: "Alexander_Pokryshkin", password: "Guest123" )
