# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create!(username: "Alexey_Stakhanov", password: "TonsOfCoal1906" )
User.create!(username: "Alexey_Stakhanov", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478234346/250px-Time_-_Stakhanov_carwkn.jpg" )
User.create!(username: "Ivan_Kozhedub", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478234368/hqdefault_qipzjp.jpg" )
User.create!(username: "Yuri_Gagarin", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478234696/7137_xtslkr.jpg" )
User.create!(username: "Valentina_Tereshkova", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478234610/valentina_tereshkova.jpg" )
User.create!(username: "Ivan_Panfilov", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478234857/Ivan_Panfilov__28painted_by_Vasily_Yakovlev_29_w18sfc.jpg" )
User.create!(username: "Dmitry_Lavrinenko", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478234931/upload-d218a8c0-ef49-11e4-8b55-33c7b22f10b9_ilhoem.png" )
User.create!(username: "Vasily_Zaytsev", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478235101/v.g.zaitsev_psk0gc.jpg" )
User.create!(username: "Lyudmila_Pavlichenko", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478234996/Pavlichenko_LM_pupd0z.jpg" )
User.create!(username: "Mariya_Oktyabrskaya", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478235235/0711_cfcl5s.jpg" )
User.create!(username: "Georgy_Zhukov", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478235308/Zhukov1923_yrj4nm.jpg" )
User.create!(username: "Konstantin_Rokossovsky", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478235370/konstantin-konstantinovich-rokossovsky-drupal1_kfwcgg.jpg" )
User.create!(username: "Ivan_Konev", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478235583/2e32054eb4a2b5b5900433d7b2e94ccd_r0z7tk.jpg" )
User.create!(username: "Aleksandr_Vasilevsky", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478235461/150px-Vasilevski1928_fnnr64.jpg" )
User.create!(username: "Markian_Popov", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478235650/popov_markian_sobi3f.gif" )
User.create!(username: "Kliment_Voroshilov", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478235903/a163d671474ccf19046d91f20165193c_hgynxz.jpg" )
User.create!(username: "Ivan_Fedyuninsky", password: "Guest123", image_url: "http://res.cloudinary.com/dmuuruew8/image/upload/v1478235977/Portrait_photo_of_Soviet_Lt._Colonel_Ivan_Fedyuninsky_during_the_Battle_of_Khalkin-Gol_2C_1938.jp9_pncbbl.jpg" )
User.create!(username: "Nikolay_Voronov", password: "Guest123", image_url: "" )
User.create!(username: "Andrey_Yeryomenko", password: "Guest123", image_url: "" )
User.create!(username: "Vasily_Chuikov", password: "Guest123", image_url: "" )
User.create!(username: "Ivan_Petrov", password: "Guest123", image_url: "" )
User.create!(username: "Filipp_Oktyabrskiy", password: "Guest123", image_url: "" )
User.create!(username: "Gordey_Levchenko", password: "Guest123", image_url: "" )
User.create!(username: "Aleksandr_Marinesko", password: "Guest123", image_url: "" )
User.create!(username: "Alexander_Matrosov", password: "Guest123", image_url: "" )
User.create!(username: "Richard_Sorge", password: "Guest123", image_url: "" )
User.create!(username: "Nikolai_Kuznetsov", password: "Guest123", image_url: "" )
User.create!(username: "Zhambyl_Tulaev", password: "Guest123", image_url: "" )
User.create!(username: "Anna_Yegorova", password: "Guest123", image_url: "" )
User.create!(username: "Alexander_Pokryshkin", password: "Guest123", image_url: "" )
