
const guestAccounts = () => (
  ["Alexey_Stakhanov",
  "Ivan_Kozhedub",
  "Yuri_Gagarin",
  "Valentina_Tereshkova",
  "Ivan_Panfilov",
  "Dmitry_Lavrinenko",
  "Vasily_Zaytsev",
  "Lyudmila_Pavlichenko",
  "Mariya_Oktyabrskaya",
  "Georgy_Zhukov",
  "Konstantin_Rokossovsky",
  "Ivan_Konev",
  "Aleksandr_Vasilevsky",
  "Markian_Popov",
  "Kliment_Voroshilov",
  "Ivan_Fedyuninsky",
  "Mikhail_Khozin",
  "Leonid_Govorov",
  "Nikolay_Voronov",
  "Andrey_Yeryomenko",
  "Vasily_Chuikov",
  "Ivan_Petrov",
  "Filipp_Oktyabrskiy",
  "Gordey_Levchenko",
  "Aleksandr_Marinesko",
  "Alexander_Matrosov",
  "Richard_Sorge",
  "Nikolai_Kuznetsov",
  "Zhambyl_Tulaev",
  "Anna_Yegorova",
  "Alexander_Pokryshkin"]
)

export default guestAccounts
